name: transit_tracer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  firebase_core: ^4.2.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  intl_phone_field: ^3.2.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  get_it: ^9.0.5
  auto_route: ^10.2.2
  firebase_storage: 13.0.4
  recase: ^4.1.0
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  email_validator: ^3.0.0
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  google_places_autocomplete_text_field: ^3.0.0
  auto_size_text: ^3.0.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.6
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo/

flutter_intl:
  enabled: true
  class_name: S 
  main_locale: en

